spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb # Use `mem` para banco em memória, `file` para persistir
    username: sa
    password: password
  h2:
    console:
      enabled: true # Ativa o console web para o H2
      path: /h2-console # Define o caminho para o console
  jpa:
    hibernate:
      ddl-auto: update # Use 'create', 'update', ou 'none' conforme necessário
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
